print("what is your name human?")
name = input ()
print("what is your age (in years)?")
age = int(input())
print("How tall are you (in meters)?")
height = float(input())
print("How much do you weigh (in kilograms)?")
weight = float(input())
print(name, "you are", age, "years old and your bmi is", weight/(height*height))