print("how many mountains should I display?")
n = int(input())
print()
print("Displaying...")
for count in range(0, n, 1):
    print("           __")
    print("          /  \_ ")
    print("         /^    \ ")
    print("        /  ^    \_")
    print("      _/ ^ ^     ^\ ")
    print("     /  ^     ^    \ ")
print()
print("Done!")