print("please enter the number of lives.")
lives = int(input ())
print("please enter the energy level.")
energy = int(input())
print("please enter the shield level.")
shield = int(input())
print()
print("health has been set.")
print()
print("Lives:", lives*"♥ ")
print("energy:", energy*"☻ ")
print("shield:", shield*"♦ ")